### ISSUE TITLE
Create better email template

### ISSUE THREAD

**Issue by mjdubell** [mjdubell/Bookie#25]
Bookie! needs a new design for the email template. It should be responsive and work for email clients.

**Comment by RodolfoFerro** [comment]
Hi Michael, I was not able to find the current email template you're using. 
Would you be able to provide more info about this issue, please?

**Comment by mjdubell** [comment]
@RodolfoFerro Email template can be found here: https://github.com/mjdubell/Bookie/blob/master/apps/web/templates/email/email.html

I'm looking for a lightweight email template, the design should look something like this: https://htmlemail.io/templates/rss, a list with bookmarks sent to the user. This could be made with https://github.com/leemunroe/responsive-html-email-template.

So the objective is to create a new HTML template that looks good on desktop and on mobile.

**Comment by RodolfoFerro** [comment]
Okay, I'm taking this one. 👀

**Comment by RodolfoFerro** [comment]
Hey @mjdubell I'm already working on this based on [this](https://htmlemail.io/templates/rss) style:
<img width="1280" alt="Screen Shot 2019-10-04 at 7 46 23 PM" src="https://user-images.githubusercontent.com/8453749/66247207-d9f02400-e6df-11e9-8253-7da413b1895e.png">

With three bookmarks it would look like this:
<img width="1280" alt="Screen Shot 2019-10-04 at 7 47 20 PM" src="https://user-images.githubusercontent.com/8453749/66247223-01df8780-e6e0-11e9-91a7-d2561b8847d4.png">

I've already tested the template and it is responsive. Please let me know what do you think.

**Comment by mjdubell** [comment]
@RodolfoFerro This is great! Create a PR and I'll check it out.

**Comment by RodolfoFerro** [comment]
Done!
Reference to https://github.com/mjdubell/Bookie/pull/43.

**Comment by mjdubell** [comment]
Fixed!
