### ISSUE TITLE
Data portability

### ISSUE THREAD

**Issue by mjdubell** [mjdubell/Bookie#3]
It should be possible to export all saved bookmarks to a `.csv` file.

**Comment by rosdyana** [comment]
Hi @mjdubell may I help you on this feature?

**Comment by mjdubell** [comment]
@rosdyana Absolutely!

**Comment by rosdyana** [comment]
@mjdubell please check my PR #42 , thanks!

**Comment by mjdubell** [comment]
Awesome, will check it out!

**Comment by mjdubell** [comment]
Fixed in #42, Thanks @rosdyana!
